// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ff0_C
arma::vec ff0_C(RObject st, int ss_dim, Nullable<IntegerVector> w_vec, Nullable<StringVector> st_vec);
RcppExport SEXP _CRFutil2_ff0_C(SEXP stSEXP, SEXP ss_dimSEXP, SEXP w_vecSEXP, SEXP st_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type st(stSEXP);
    Rcpp::traits::input_parameter< int >::type ss_dim(ss_dimSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type w_vec(w_vecSEXP);
    Rcpp::traits::input_parameter< Nullable<StringVector> >::type st_vec(st_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(ff0_C(st, ss_dim, w_vec, st_vec));
    return rcpp_result_gen;
END_RCPP
}
// ff1_C
arma::vec ff1_C(double st, double ss_dim, arma::vec w_vec, arma::vec st_vec);
RcppExport SEXP _CRFutil2_ff1_C(SEXP stSEXP, SEXP ss_dimSEXP, SEXP w_vecSEXP, SEXP st_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type st(stSEXP);
    Rcpp::traits::input_parameter< double >::type ss_dim(ss_dimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w_vec(w_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type st_vec(st_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(ff1_C(st, ss_dim, w_vec, st_vec));
    return rcpp_result_gen;
END_RCPP
}
// ff2_C
arma::uvec ff2_C(double st, arma::vec st_vec);
RcppExport SEXP _CRFutil2_ff2_C(SEXP stSEXP, SEXP st_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type st(stSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type st_vec(st_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(ff2_C(st, st_vec));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_prototypef
List rcpp_prototypef();
RcppExport SEXP _CRFutil2_rcpp_prototypef() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_prototypef());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CRFutil2_ff0_C", (DL_FUNC) &_CRFutil2_ff0_C, 4},
    {"_CRFutil2_ff1_C", (DL_FUNC) &_CRFutil2_ff1_C, 4},
    {"_CRFutil2_ff2_C", (DL_FUNC) &_CRFutil2_ff2_C, 2},
    {"_CRFutil2_rcpp_prototypef", (DL_FUNC) &_CRFutil2_rcpp_prototypef, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_CRFutil2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
