# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title       One-body (node) energy function
#' @description One-body (node) energy function
#'
#' @param yA  a node state
#' @param tA  tau vector
#' @param ff  feature function
#' @param dots list of optional arguments for feature function
#'
#' @details One-body (node) energy function
#'
#' @return One-body (node) energy.
#'
#' @examples # node weights:
#'tau2 <- c( 1, -1.3)
#'tau3 <- c( 1, -1.3, 0.1)
#'
#'Eone_C(yA = 2, tA = tau3, ff = ff1_C, list(nss.dim=3))
#'Eone_C(yA = 3, tA = tau3, ff = ff1_C, list(nss.dim=3))
#'Eone_C(yA = 2, tA = tau2, ff = ff1_C)
#'Eone_C(yA = "a", tA = tau3, ff = ff1_C, list(nss.vec = c("a", "b", "c")))
#'Eone_C(yA = 2, tA = tau2, ff = ff0_C)
#'Eone_C(yA = 1, tA = tau2, ff = ff0_C)
#'Eone_C(yA = 3, tA = tau2, ff = ff0_C) # Throws error because less general ff0 used
#'
Eone_C <- function(yA, tA, ff, dots = NULL) {
    .Call(`_CRFutil2_Eone_C`, yA, tA, ff, dots)
}

#' @title       Two-body (edge) energy function
#' @description Two-body (edge) energy function
#'
#' @param yA   node A state
#' @param yB   node B state
#' @param wAB  omega matrix
#' @param ff   feature function
#' @param dots list of optional arguments for feature function
#'
#' @details Two-body (edge) energy function
#'
#' @return Two-body (edge) energy.
#'
#' @examples # edge weights:
#'omega22 <- rbind(
#'  c( 3.5, -1.4),
#'  c(-1.4,  2.5)
#')
#'
#'omega33 <- rbind(
#'  c( 3.5, -1.4,   2.5),
#'  c(-1.4,  2.5,  -0.8),
#'  c( 3.8,  0.95, -7.6)
#')
#'
#' Etwo_C(yA = 2, yB = 1, wAB = omega22, ff = ff1_C, list(nss.dim=2))
#' Etwo_C(yA = 2, yB = 1, wAB = omega22, ff = ff1_C, list(nss.dim=3)) # Throws error
#' Etwo_C(yA = 2, yB = 2, wAB = omega33, ff = ff1_C, list(nss.dim=3)) # Throws error
#' Etwo_C(yA = "c", yB = "b", wAB = omega33, ff = ff1_C, list(nss.vec=c("a", "b", "c")))
#'
#' Etwo_C(yA = 2, yB = 1, wAB = omega22, ff = ff0_C)
#' Etwo_C(yA = 2, yB = 1, wAB = omega33, ff = ff0_C)
#' Etwo_C(yA = 2, yB = 1, wAB = omega33, ff = ff1_C) # Throws error bec nss.dim=2 assumed
#' Etwo_C(yA = 2, yB = 1, wAB = omega22, ff = ff1_C)
#'
Etwo_C <- function(yA, yB, wAB, ff, dots = NULL) {
    .Call(`_CRFutil2_Etwo_C`, yA, yB, wAB, ff, dots)
}

#' @title       Stripped down version of ff0_C. No checking. Not idiot proof.
#' @description Built-in feature function for convenience and testing.
#'
#' @param st     State label
#' @param ss_dim State space dimension. Minimum is 2 (Ising), but function doesn't check.
#' @param w_vec  Weight vector. Needs to be of length ss_dim.
#' @param st_vec Vector for state names. Needs to be of length ss_dim.
#'
#' @details Stripped down version of ff0_C. No checking. Not idiot proof. Meant to be faster. Runs about as fast as ff0 on the R side.
#'
#' @return The feature function, which is a arma vector.
#'
ff01_C <- function(st, ss_dim, w_vec, st_vec) {
    .Call(`_CRFutil2_ff01_C`, st, ss_dim, w_vec, st_vec)
}

#' @title       Very stripped down version of ff0_C. No checking and assumes unit weighted states.
#' @description Built-in feature function for convenience and testing.
#'
#' @param st     State label
#' @param st_vec Vector for state names. Needs to be at least two (numerical) components.
#'
#' @details Very stripped down version of ff0_C. Runs fastest of the three: ff0_C, ff1_C and ff2_C.
#'
#' @return The feature function, which is a arma unsigned vector.
#'
ff02_C <- function(st, st_vec) {
    .Call(`_CRFutil2_ff02_C`, st, st_vec)
}

#' @title       Feature function in Rcpp
#' @description Built-in feature function for convenience and testing. Works pretty much like ff0 on the R side.
#'
#' @param st     State label
#' @param ss_dim State space dimension. Default is 2 (Ising)
#' @param w_vec  Optional weight vector
#' @param st_vec Optional vector for state names
#'
#' @details The function is a handy feature function for testing. It can handle both Ising and Potts state spaces. Surprisingly though this is twice as slow as ff0....
#'
#' @return The feature function, which is a arma vector.
#'
#' @examples ff0_C(st = 3, ss_dim = 4, st_vec = c(0,1,2,3))
#' ff0_C(st = "a", st_vec = c("a","b"))
#' ff0_C(st = "ID", ss.dim = 3, st.vec = c("ID","exclude","inconclusive"))
#' ff0_C(1)
#' ff0_C(1,3)
#' ff0_C(st = "b")           # Throws error
#' ff0_C(st = 5)             # Throws error
#' ff0_C(st = 5, ss_dim = 4) # Throws error
#'
ff0_C <- function(st, ss_dim = 2L, w_vec = NULL, st_vec = NULL) {
    .Call(`_CRFutil2_ff0_C`, st, ss_dim, w_vec, st_vec)
}

#' @title       A stripped down version of ff1_C. No checking, assumes unit weighted states and integer 1:(node state space dimension) node state names.
#' @description Built-in feature function for convenience and testing.
#'
#' @param ns      State label
#' @param nss_vec Vector for state names. Use in place of dots arguement.
#'
#' @details A stripped down version of ff1_C. Built for speed....I hope.
#'
#' @return The feature function, which is a arma unsigned vector.
#'
ff11_C <- function(ns, dots) {
    .Call(`_CRFutil2_ff11_C`, ns, dots)
}

#' @title       Very stripped down version of ff1_C. No checking, assumes unit weighted states and integer 1:(node state space dimension) node state names.
#' @description Built-in feature function for convenience and testing.
#'
#' @param ns      State label
#' @param nss_vec Vector for state names. Use in place of dots arguement.
#'
#' @details Very stripped down version of ff1_C. Needs a helper R wrapper (ff12_RC()) because of the whole dots thing.
#' Built for speed....I hope.
#'
#' @return The feature function, which is a arma unsigned vector.
#'
ff12_C <- function(ns, nss_vec) {
    .Call(`_CRFutil2_ff12_C`, ns, nss_vec)
}

#' @title        Very ver stripped down version of ff1_C. No checking, assumes unit weighted states and integer node state names starting at 1.
NULL

ff13_C <- function(ns, nss_dim) {
    .Call(`_CRFutil2_ff13_C`, ns, nss_dim)
}

#' @title       Feature function in Rcpp
#' @description Built-in feature function for convenience and testing. Works pretty much like ff1 on the R side.
#'
#' @param ns     state label of node (\emph{i.e.} node state)
#' @param dots   Optional arguments: \cr
#'               \describe{
#'                 \item{\code{nss.vec}}{node state space (a vector)}
#'                 \item{\code{nss.dim}}{node state space dimension}
#'                 \item{\code{w.vec}}{node state space weight vector}
#'               }
#'
#' @details The function is a handy feature function for testing. It can handle both Ising and Potts state spaces. Surprisingly though this is 2X-4X as slow as ff0.... WHY??
#'
#' @return The feature function, which is a arma vector.
#'
#' @examples XXXX
#'
ff1_C <- function(ns, dots = NULL) {
    .Call(`_CRFutil2_ff1_C`, ns, dots)
}

#' @title       Feature function in Rcpp example with timers via RcppClock
#' @description Built-in feature function for convenience and testing. Works pretty much like ff1 on the R side.
#'
#' @param ns     state label of node (\emph{i.e.} node state)
#' @param dots   Optional arguments: \cr
#'               \describe{
#'                 \item{\code{nss.vec}}{node state space (a vector)}
#'                 \item{\code{nss.dim}}{node state space dimension}
#'                 \item{\code{w.vec}}{node state space weight vector}
#'               }
#'
#' @details Example function with timers via RcppClock for timing execution on blocks of code.
#' This is also part of experiments to explore why ff1_C runs 2X-4X as slow as ff0.
#'
#' @return The feature function, which is a arma vector.
#'
#' @examples XXXX
#'
ff1_times_C <- function(ns, dots = NULL) {
    .Call(`_CRFutil2_ff1_times_C`, ns, dots)
}

#' @title        XX function
#' @description XX
#'
#' @param XX    XX
#'
#' @details The function XX
#'
#' @return  XX
#'
#' @examples XXXX
#'
rcpp_prototypef <- function() {
    .Call(`_CRFutil2_rcpp_prototypef`)
}

#' @title       Compare an element to elements in a vector
#' @description Compare an element to elements in a vector, independent of data type.
#'
#' @param element Something to compare to. Can be any single element RObject
#' @param vector A vector of things to compare element to. Can be any types.
#'
#' @details Sometime when comparing RObjects of arbitrary type doesn't work right because the wrong type
#' is guessed, i.e. element RObject cast to a hex code for a char but needs it to be interpreted as a hex
#' code for a string. This function just casts EVERYTHING to char hex codes using Rf_asChar(). This trick
#' seems to work.
#'
#' @return An (arma) indicator vector. 1 means element same as vector's element and 0 otherwise.
#'
#' @examples XXXX
#'
compare_element <- function(element, vector) {
    .Call(`_CRFutil2_compare_element`, element, vector)
}

#' @title Check if element is in a vector
#' @description Check if element is in a vector, independent of data type.
#'
#' @param element Something to compare to. Can be any single element RObject
#' @param vector A vector of things to compare element to. Can be any types.
#'
#' @details I'm tired of writing this out longhand in the codes so writing a wrapper.
#'
#' @return A bool. 1 = element in vector, 0 otherwise
#'
#' @examples XXXX
#'
inQ <- function(element, vector) {
    .Call(`_CRFutil2_inQ`, element, vector)
}

