# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title        XX function
#' @description XX
#'
#' @param XX    XX
#'
#' @details The function XX
#'
#' @return  XX
#'
#' @examples XXXX
#'
Eone_C <- function(yA, tA, ff, dots = NULL) {
    .Call(`_CRFutil2_Eone_C`, yA, tA, ff, dots)
}

#' @title       Stripped down version of ff0_C. No checking. Not idiot proof.
#' @description Built-in feature function for convenience and testing.
#'
#' @param st     State label
#' @param ss_dim State space dimension. Minimum is 2 (Ising), but function doesn't check.
#' @param w_vec  Weight vector. Needs to be of length ss_dim.
#' @param st_vec Vector for state names. Needs to be of length ss_dim.
#'
#' @details Stripped down version of ff0_C. No checking. Not idiot proof. Meant to be faster. Runs about as fast as ff0 on the R side.
#'
#' @return The feature function, which is a arma vector.
#'
ff01_C <- function(st, ss_dim, w_vec, st_vec) {
    .Call(`_CRFutil2_ff01_C`, st, ss_dim, w_vec, st_vec)
}

#' @title       Very stripped down version of ff0_C. No checking and assumes unit weighted states.
#' @description Built-in feature function for convenience and testing.
#'
#' @param st     State label
#' @param st_vec Vector for state names. Needs to be at least two (numerical) components.
#'
#' @details Very stripped down version of ff0_C. Runs fastest of the three: ff0_C, ff1_C and ff2_C.
#'
#' @return The feature function, which is a arma unsigned vector.
#'
ff02_C <- function(st, st_vec) {
    .Call(`_CRFutil2_ff02_C`, st, st_vec)
}

#' @title       Feature function in Rcpp
#' @description Built-in feature function for convenience and testing. Works pretty much like ff0 on the R side.
#'
#' @param st     State label
#' @param ss_dim State space dimension. Default is 2 (Ising)
#' @param w_vec  Optional weight vector
#' @param st_vec Optional vector for state names
#'
#' @details The function is a handy feature function for testing. It can handle both Ising and Potts state spaces. Surprisingly though this is twice as slow as ff0....
#'
#' @return The feature function, which is a arma vector.
#'
#' @examples ff0_C(st = 3, ss_dim = 4, st_vec = c(0,1,2,3))
#' ff0_C(st = "a", st_vec = c("a","b"))
#' ff0_C(st = "ID", ss.dim = 3, st.vec = c("ID","exclude","inconclusive"))
#' ff0_C(1)
#' ff0_C(1,3)
#' ff0_C(st = "b")           # Throws error
#' ff0_C(st = 5)             # Throws error
#' ff0_C(st = 5, ss_dim = 4) # Throws error
#'
ff0_C <- function(st, ss_dim = 2L, w_vec = NULL, st_vec = NULL) {
    .Call(`_CRFutil2_ff0_C`, st, ss_dim, w_vec, st_vec)
}

#' @title       Feature function in Rcpp
#' @description Built-in feature function for convenience and testing. Works pretty much like ff1 on the R side.
#'
#' @param ns     state label of node (\emph{i.e.} node state)
#' @param dots   Optional arguments: \cr
#'               \describe{
#'                 \item{\code{nss.vec}}{node state space (a vector)}
#'                 \item{\code{nss.dim}}{node state space dimension}
#'                 \item{\code{w.vec}}{node state space weight vector}
#'               }
#'
#' @details The function is a handy feature function for testing. It can handle both Ising and Potts state spaces. Surprisingly though this is 2X-4X as slow as ff0.... WHY??
#'
#' @return The feature function, which is a arma vector.
#'
#' @examples XXXX
#'
ff1_C <- function(ns, dots = NULL) {
    .Call(`_CRFutil2_ff1_C`, ns, dots)
}

#' @title        XX function
NULL

rcpp_prototypef <- function() {
    .Call(`_CRFutil2_rcpp_prototypef`)
}

#' @title       Compare an element to elements in a vector
#' @description Compare an element to elements in a vector, independent of data type.
#'
#' @param element Something to compare to. Can be any single element RObject
#' @param vector A vector of things to compare element to. Can be any types.
#'
#' @details Sometime when comparing RObjects of arbitrary type doesn't work right because the wrong type
#' is guessed, i.e. element RObject cast to a hex code for a char but needs it to be interpreted as a hex
#' code for a string. This function just casts EVERYTHING to char hex codes using Rf_asChar(). This trick
#' seems to work.
#'
#' @return An (arma) indicator vector. 1 means element same as vector's element and 0 otherwise.
#'
#' @examples XXXX
#'
compare_element <- function(element, vector) {
    .Call(`_CRFutil2_compare_element`, element, vector)
}

#' @title Check if element is in a vector
#' @description Check if element is in a vector, independent of data type.
#'
#' @param element Something to compare to. Can be any single element RObject
#' @param vector A vector of things to compare element to. Can be any types.
#'
#' @details I'm tired of writing this out longhand in the codes so writing a wrapper.
#'
#' @return A bool. 1 = element in vector, 0 otherwise
#'
#' @examples XXXX
#'
inQ <- function(element, vector) {
    .Call(`_CRFutil2_inQ`, element, vector)
}

