# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title       Feature function in Rcpp
#' @description Built-in feature function for convenience and testing. Works pretty much like ff0 on the R side.
#'
#' @param st     State label
#' @param ss_dim State space dimension. Default is 2 (Ising)
#' @param w_vec  Optional weight vector
#' @param st_vec Optional vector for state names
#'
#' @details The function is a handy feature function for testing. It can handle both Ising and Potts state spaces. Surprisingly though this is twice as slow as ff0....
#'
#' @return The feature function, which is a arma vector.
#'
#' @examples ff0_C(st = 3, ss_dim = 4, st_vec = c(0,1,2,3))
#' ff0_C(st = "a", st_vec = c("a","b"))
#' ff0_C(st = "ID", ss.dim = 3, st.vec = c("ID","exclude","inconclusive"))
#' ff0_C(1)
#' ff0_C(1,3)
#' ff0_C(st = "b")           # Throws error
#' ff0_C(st = 5)             # Throws error
#' ff0_C(st = 5, ss_dim = 4) # Throws error
#'
ff0_C <- function(st, ss_dim = 2L, w_vec = NULL, st_vec = NULL) {
    .Call(`_CRFutil2_ff0_C`, st, ss_dim, w_vec, st_vec)
}

#' @title       Stripped down version of ff0_C. No checking. Not idiot proof.
#' @description Built-in feature function for convenience and testing.
#'
#' @param st     State label
#' @param ss_dim State space dimension. Minimum is 2 (Ising), but function doesn't check.
#' @param w_vec  Weight vector. Needs to be of length ss_dim.
#' @param st_vec Vector for state names. Needs to be of length ss_dim.
#'
#' @details Stripped down version of ff0_C. No checking. Not idiot proof. Meant to be faster. Runs about as fast as ff0 on the R side.
#'
#' @return The feature function, which is a arma vector.
#'
ff1_C <- function(st, ss_dim, w_vec, st_vec) {
    .Call(`_CRFutil2_ff1_C`, st, ss_dim, w_vec, st_vec)
}

#' @title       Very stripped down version of ff0_C. No checking and assumes unit weighted states.
#' @description Built-in feature function for convenience and testing.
#'
#' @param st     State label
#' @param st_vec Vector for state names. Needs to be at least two (numerical) components.
#'
#' @details Very stripped down version of ff0_C. Runs fastest of the three: ff0_C, ff1_C and ff2_C.
#'
#' @return The feature function, which is a arma unsigned vector.
#'
ff2_C <- function(st, st_vec) {
    .Call(`_CRFutil2_ff2_C`, st, st_vec)
}

rcpp_prototypef <- function() {
    .Call(`_CRFutil2_rcpp_prototypef`)
}

