#' @title       Dress a sample with node and state names in crf object
#' @description Dress a sample with node and state names in crf object
#'
#' @param crf     A crf object which also contains node and state names (i.e. out augmented crf object)
#' @param samples The samples generated by one of the CRF sampling functions
#'
#' @details The function will dress up a sample configuration matrix with node names as the columns
#' and state names for the configuration outcome elements. The sampling functions from CRF
#' (e.g. sample.junction()) just spit out an undressed matrix of samples with sample state numbers
#' (e.g. 1, 2, ....) for the configuration elements. This is needed sometimes and often more
#' convenient, but for diplay purposes the user may want more labels on the sample space. Hence this
#' (cosmetic) function.
#'
#' @return The sample dressed with node and state names contained in the crf object.
#'
#' @examples XXXX
#'
#' @export
dress.sample <- function(crf, samples) {

  # Node names
  nod.nms <- crf$node.name.tab$name # **NOTE: columns of samples SHOULD be in the same order

  # Initialize the sample matrix that will have the node and state names:
  samples.dressed           <- samples # The state names in each column are converted in the loop below
  colnames(samples.dressed) <- nod.nms

  # Node names in the state label LIST. Get this in case the order is different than in nod.nms,
  # i.e. if the order of crf$node.name.tab$name and crf$node.state.names do not match for
  # some reason.
  nod.nms.st.list <- names(crf$node.state.names)

  # Loop over the nodes, which should be the columns of the sample.
  # **NOTE: this assumes the column numbers correspond the the order of the names in nod.nms
  for(i in 1:length(nod.nms)){
    nod.idx    <- which(nod.nms.st.list == nod.nms[i])
    nod.st.nms <- crf$node.state.names[[nod.idx]] # Should be the names of the states of the node
    #print(nod.st.nms)
    samples.dressed[,i] <- nod.st.nms[samples[,i]] # **NOTE: this assumes the state labels in samples are state indices, i.e. the sample was generated by one of the CRF sampling functions like sample.junction()
  }

  return(samples.dressed)

}


#' @title       Simulate a sample
#' @description Wrapper for CRF simulation functions.
#'
#' @param crf               a crf object
#' @param size              number of samples
#' @param crf.sample.method sampling method in CRF: sample.exact, .junction, .conditional, .cutset
#' @param dress.sampleQ     use the default state names from the CRF sampler or dress up with the state names stipulated in the crf object?
#' @param ...               other arguments needed for CRF sampling methods
#'
#' @details The function is a wrapper for the CRF simulation functions which knits them all
#' into one function and allows the user to change the default state names (1,2,...etc) into
#' whatever their state names are actually intended to be.
#'
#' @return A sample of configurations.
#'
#' @examples XXXX
#'
#' @export
sample.crf <- function(crf, size, crf.sample.method, dress.sampleQ=F, ...) {

  a.samp <- crf.sample.method(crf, size, ...)
  if(dress.sampleQ == T){
    a.samp <- dress.sample(crf, samples = a.samp)
  }

  return(a.samp)

}
